name: Create and publish Docker image

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: autoscaler-frontend

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Log in
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: enable emulation
        run:  docker buildx create --use &&
              docker run --rm --privileged multiarch/qemu-user-static --reset -p yes &&
              docker buildx inspect --bootstrap

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/aau-p9s/autoscaler-frontend:latest
          platforms: 
            linux/amd64