name: Dotnet Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8"
      #    cache: true # uncomment if we are gonna use external dependencies
      #- name: Restore Cache
      #  run: dotnet restore --locked-mode
      - name: Build Application
        run: dotnet build Autoscaler -c Release
